name: Mirror PPD CSV (latest)
on:
  schedule:
    - cron: "5 6 * * *"   # her gün 06:05 UTC (TR ~09:05)
  workflow_dispatch:
  
permissions:
  contents: write 
  
jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download latest available monthly CSV (with relay fallback)
        run: |
          set -e
          Y=$(date -u +%Y)
          M=$(date -u +%m)
          # last completed month
          if [ "$M" = "01" ]; then Y=$((Y-1)); M=12; else M=$(printf "%02d" $((10#$M-1))); fi

          found=""
          for i in $(seq 0 5); do
            MM=$(printf "%02d" $((10#$M)))
            PRIMARY="https://prod.publicdata.landregistry.gov.uk/ppd/monthly/pp-${Y}-${MM}.csv"
            FALLBACK="https://landregistry.data.gov.uk/app/ppd/ppd_data_monthly_report/download?month=${Y}-${MM}&format=csv"
            # relay (DNS/530/geo sorunlarına karşı)
            R_PRIMARY="https://r.jina.ai/http://prod.publicdata.landregistry.gov.uk/ppd/monthly/pp-${Y}-${MM}.csv"
            R_FALLBACK="https://r.jina.ai/http://landregistry.data.gov.uk/app/ppd/ppd_data_monthly_report/download?month=${Y}-${MM}&format=csv"

            echo "Trying ${Y}-${MM} (primary direct)…"
            if curl -fsSL --connect-timeout 10 --max-time 60 "$PRIMARY" -o latest.csv ; then
              found="${Y}-${MM} (primary direct)"; break
            fi
            echo "Trying ${Y}-${MM} (primary relay)…"
            if curl -fsSL --connect-timeout 10 --max-time 60 "$R_PRIMARY" -o latest.csv ; then
              found="${Y}-${MM} (primary relay)"; break
            fi

            echo "Trying ${Y}-${MM} (fallback direct)…"
            if curl -fsSL --connect-timeout 10 --max-time 60 "$FALLBACK" -o latest.csv ; then
              found="${Y}-${MM} (fallback direct)"; break
            fi
            echo "Trying ${Y}-${MM} (fallback relay)…"
            if curl -fsSL --connect-timeout 10 --max-time 60 "$R_FALLBACK" -o latest.csv ; then
              found="${Y}-${MM} (fallback relay)"; break
            fi

            # one month back
            if [ "$M" = "01" ]; then Y=$((Y-1)); M=12; else M=$(printf "%02d" $((10#$M-1))); fi
          done

          if [ -z "$found" ]; then
            echo "No monthly CSV found in last 6 months."; exit 1
          fi
          echo "Downloaded: $found"

          # Header yoksa ekle
          if ! head -n 1 latest.csv | grep -qi 'price'; then
            (echo 'Price,Date of Transfer,Postcode,PAON,SAON,Street,Locality,Town/City,District,County' && cat latest.csv) > latest.tmp
            mv latest.tmp latest.csv
          fi

      - name: Commit file
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git add latest.csv
          git commit -m "update latest.csv" || echo "no changes"
          git push
